version: '3.8'

services:
  server:
    container_name: api
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "4000:80"


networks:
  default:
    name: products
    external: true
