version: "3.8"

services:
  server:
    container_name: websockets-server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
        - USER=${USER:-websockets}
    entrypoint: ["npm"]
    command: ["run", "start:dev"]
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=5001
      - REDIS_HOST=redis://websockets-redis:6379
    ports:
      - "5001:5001"
    depends_on:
      - redis
  consumer:
    container_name: websockets-consumer
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
        - USER=${USER:-websockets}
    entrypoint: ["npm"]
    command: ["run", "start:consumer:dev"]
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis://websockets-redis:6379
    depends_on:
      - redis
  redis:
    container_name: websockets-redis
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: products
